seed: 0
exp_name: multi_community_kto_usa_debug
batch_size: 32
eval_batch_size: 32
debug: false
fsdp_port: 33101
datasets:
- Binwei01/mmoqa_usa
wandb:
  enabled: true
  entity: null
  project: direct-preference-optimization
local_dirs:
- /scr-ssd
- /scr
- .cache
sample_during_eval: false
n_eval_model_samples: 16
do_first_eval: true
local_run_dir: .
lr: 5.0e-07
gradient_accumulation_steps: 8
max_grad_norm: 10.0
max_length: 512
max_prompt_length: 256
n_epochs: 20
n_examples: null
n_eval_examples: 256
trainer: FSDPTrainer
optimizer: RMSprop
warmup_steps: 150
activation_checkpointing: false
eval_every: 9984
minimum_log_interval_secs: 1.0
output_dir: /data/binwei/dpo/outputs/kto-usa-data-debug
patience: 4
eval_metric: loss/eval
model:
  name_or_path: gpt2-large
  tokenizer_name_or_path: null
  archive: /data/binwei/dpo/outputs/sft-number/step-379392/policy.pt
  block_name: GPT2Block
  policy_dtype: float32
  fsdp_policy_mp: bfloat16
  reference_dtype: float16
loss:
  name: kto
  beta: 0.1
  desirable_weight: 1.0
  undesirable_weight: 1.0
  reference_free: false
